# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luk_operator_prototype_upd_1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ctgt = QtWidgets.QLCDNumber(self.centralwidget)
        self.ctgt.setGeometry(QtCore.QRect(460, 330, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 176, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ctgt.setPalette(palette)
        self.ctgt.setAutoFillBackground(True)
        self.ctgt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ctgt.setDigitCount(5)
        self.ctgt.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ctgt.setProperty("value", 57.5)
        self.ctgt.setProperty("intValue", 57)
        self.ctgt.setObjectName("ctgt")
        self.vtg = QtWidgets.QLabel(self.centralwidget)
        self.vtg.setGeometry(QtCore.QRect(0, -60, 914, 594))
        self.vtg.setText("")
        self.vtg.setPixmap(QtGui.QPixmap("img/втг.png"))
        self.vtg.setScaledContents(True)
        self.vtg.setObjectName("vtg")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(260, 470, 731, 192))
        self.log.setObjectName("log")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(110, 470, 140, 48))
        self.btn_start.setObjectName("btn_start")
        self.gtu_static = QtWidgets.QLabel(self.centralwidget)
        self.gtu_static.setGeometry(QtCore.QRect(0, -60, 914, 594))
        self.gtu_static.setText("")
        self.gtu_static.setPixmap(QtGui.QPixmap("raw_img/гту_0.png"))
        self.gtu_static.setScaledContents(True)
        self.gtu_static.setObjectName("gtu_static")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(440, 330, 20, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 176, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 40, 160, 310))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.zugt = QtWidgets.QLabel(self.frame)
        self.zugt.setGeometry(QtCore.QRect(100, 10, 48, 48))
        self.zugt.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zugt.setScaledContents(True)
        self.zugt.setObjectName("zugt")
        self.zuku = QtWidgets.QLabel(self.frame)
        self.zuku.setGeometry(QtCore.QRect(100, 70, 48, 48))
        self.zuku.setText("")
        self.zuku.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zuku.setScaledContents(True)
        self.zuku.setObjectName("zuku")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.zapg = QtWidgets.QLabel(self.frame)
        self.zapg.setGeometry(QtCore.QRect(100, 130, 48, 48))
        self.zapg.setText("")
        self.zapg.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zapg.setScaledContents(True)
        self.zapg.setObjectName("zapg")
        self.zagb = QtWidgets.QLabel(self.frame)
        self.zagb.setGeometry(QtCore.QRect(100, 190, 48, 48))
        self.zagb.setText("")
        self.zagb.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zagb.setScaledContents(True)
        self.zagb.setObjectName("zagb")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.ss = QtWidgets.QLabel(self.frame)
        self.ss.setGeometry(QtCore.QRect(100, 250, 48, 48))
        self.ss.setText("")
        self.ss.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.ss.setScaledContents(True)
        self.ss.setObjectName("ss")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(850, 40, 140, 380))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_gt = QtWidgets.QPushButton(self.frame_2)
        self.btn_gt.setGeometry(QtCore.QRect(10, 20, 120, 25))
        self.btn_gt.setObjectName("btn_gt")
        self.btn_ku = QtWidgets.QPushButton(self.frame_2)
        self.btn_ku.setGeometry(QtCore.QRect(10, 80, 120, 25))
        self.btn_ku.setObjectName("btn_ku")
        self.btn_vtg = QtWidgets.QPushButton(self.frame_2)
        self.btn_vtg.setGeometry(QtCore.QRect(10, 260, 120, 25))
        self.btn_vtg.setObjectName("btn_vtg")
        self.btn_pg = QtWidgets.QPushButton(self.frame_2)
        self.btn_pg.setGeometry(QtCore.QRect(10, 140, 120, 25))
        self.btn_pg.setObjectName("btn_pg")
        self.btn_gb = QtWidgets.QPushButton(self.frame_2)
        self.btn_gb.setGeometry(QtCore.QRect(10, 200, 120, 25))
        self.btn_gb.setObjectName("btn_gb")
        self.btn_call = QtWidgets.QPushButton(self.frame_2)
        self.btn_call.setGeometry(QtCore.QRect(10, 320, 120, 48))
        self.btn_call.setObjectName("btn_call")
        self.gtu_static.raise_()
        self.vtg.raise_()
        self.ctgt.raise_()
        self.label_8.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.log.raise_()
        self.btn_start.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тренажер оператора ГТУ"))
        self.btn_start.setText(_translate("MainWindow", "Запустить\n"
"демо-сценарий"))
        self.label_8.setText(_translate("MainWindow", "T"))
        self.label_2.setText(_translate("MainWindow", "ЗУ КУ"))
        self.label.setText(_translate("MainWindow", "ЗУ ГТ"))
        self.label_3.setText(_translate("MainWindow", "ЗА ПГ"))
        self.label_4.setText(_translate("MainWindow", "ЗА ГБ"))
        self.label_5.setText(_translate("MainWindow", "СС"))
        self.btn_gt.setText(_translate("MainWindow", "Закрыть ЗУ ГТ"))
        self.btn_ku.setText(_translate("MainWindow", "Закрыть ЗУ КУ"))
        self.btn_vtg.setText(_translate("MainWindow", "Включить ВТГ"))
        self.btn_pg.setText(_translate("MainWindow", "Открыть ЗА ПГ"))
        self.btn_gb.setText(_translate("MainWindow", "Открыть ЗА ГБ"))
        self.btn_call.setText(_translate("MainWindow", "Звонок\n"
"диспетчеру"))

