# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luk_operator_prototype_upd_2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 665)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 665))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 665))
        self.centralwidget.setObjectName("centralwidget")
        self.ctgt = QtWidgets.QLCDNumber(self.centralwidget)
        self.ctgt.setGeometry(QtCore.QRect(460, 330, 71, 31))
        self.ctgt.setMinimumSize(QtCore.QSize(71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 176, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ctgt.setPalette(palette)
        self.ctgt.setAutoFillBackground(True)
        self.ctgt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ctgt.setDigitCount(5)
        self.ctgt.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ctgt.setProperty("value", 57.0)
        self.ctgt.setProperty("intValue", 57)
        self.ctgt.setObjectName("ctgt")
        self.vtg = QtWidgets.QLabel(self.centralwidget)
        self.vtg.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtg.sizePolicy().hasHeightForWidth())
        self.vtg.setSizePolicy(sizePolicy)
        self.vtg.setMinimumSize(QtCore.QSize(914, 594))
        self.vtg.setText("")
        self.vtg.setPixmap(QtGui.QPixmap("img/втг.png"))
        self.vtg.setScaledContents(True)
        self.vtg.setObjectName("vtg")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(260, 470, 731, 192))
        self.log.setMinimumSize(QtCore.QSize(730, 190))
        self.log.setObjectName("log")
        self.btn_start_demo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_demo.setGeometry(QtCore.QRect(110, 470, 140, 48))
        self.btn_start_demo.setMinimumSize(QtCore.QSize(140, 48))
        self.btn_start_demo.setObjectName("btn_start_demo")
        self.gtu_static = QtWidgets.QLabel(self.centralwidget)
        self.gtu_static.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gtu_static.sizePolicy().hasHeightForWidth())
        self.gtu_static.setSizePolicy(sizePolicy)
        self.gtu_static.setMinimumSize(QtCore.QSize(914, 594))
        self.gtu_static.setText("")
        self.gtu_static.setPixmap(QtGui.QPixmap("raw_img/гту_0.png"))
        self.gtu_static.setScaledContents(True)
        self.gtu_static.setObjectName("gtu_static")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(440, 330, 20, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(20, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 176, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 40, 160, 310))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(160, 310))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 70, 48))
        self.label_2.setMinimumSize(QtCore.QSize(70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 70, 48))
        self.label.setMinimumSize(QtCore.QSize(70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.zugt = QtWidgets.QLabel(self.frame)
        self.zugt.setGeometry(QtCore.QRect(100, 10, 48, 48))
        self.zugt.setMinimumSize(QtCore.QSize(48, 48))
        self.zugt.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zugt.setScaledContents(True)
        self.zugt.setObjectName("zugt")
        self.zuku_2 = QtWidgets.QLabel(self.frame)
        self.zuku_2.setGeometry(QtCore.QRect(100, 70, 48, 48))
        self.zuku_2.setMinimumSize(QtCore.QSize(48, 48))
        self.zuku_2.setText("")
        self.zuku_2.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zuku_2.setScaledContents(True)
        self.zuku_2.setObjectName("zuku_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 70, 48))
        self.label_3.setMinimumSize(QtCore.QSize(70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.zapg = QtWidgets.QLabel(self.frame)
        self.zapg.setGeometry(QtCore.QRect(100, 130, 48, 48))
        self.zapg.setMinimumSize(QtCore.QSize(48, 48))
        self.zapg.setText("")
        self.zapg.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zapg.setScaledContents(True)
        self.zapg.setObjectName("zapg")
        self.zagb = QtWidgets.QLabel(self.frame)
        self.zagb.setGeometry(QtCore.QRect(100, 190, 48, 48))
        self.zagb.setMinimumSize(QtCore.QSize(48, 48))
        self.zagb.setText("")
        self.zagb.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.zagb.setScaledContents(True)
        self.zagb.setObjectName("zagb")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 70, 48))
        self.label_4.setMinimumSize(QtCore.QSize(70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.ss = QtWidgets.QLabel(self.frame)
        self.ss.setGeometry(QtCore.QRect(100, 250, 48, 48))
        self.ss.setMinimumSize(QtCore.QSize(48, 48))
        self.ss.setText("")
        self.ss.setPixmap(QtGui.QPixmap("img/temp.png"))
        self.ss.setScaledContents(True)
        self.ss.setObjectName("ss")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 70, 48))
        self.label_5.setMinimumSize(QtCore.QSize(70, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(850, 40, 140, 380))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(140, 380))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_gt = QtWidgets.QPushButton(self.frame_2)
        self.btn_gt.setGeometry(QtCore.QRect(10, 20, 120, 25))
        self.btn_gt.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_gt.setObjectName("btn_gt")
        self.btn_ku = QtWidgets.QPushButton(self.frame_2)
        self.btn_ku.setGeometry(QtCore.QRect(10, 80, 120, 25))
        self.btn_ku.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_ku.setObjectName("btn_ku")
        self.btn_vtg = QtWidgets.QPushButton(self.frame_2)
        self.btn_vtg.setGeometry(QtCore.QRect(10, 260, 120, 25))
        self.btn_vtg.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_vtg.setObjectName("btn_vtg")
        self.btn_pg = QtWidgets.QPushButton(self.frame_2)
        self.btn_pg.setGeometry(QtCore.QRect(10, 140, 120, 25))
        self.btn_pg.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_pg.setObjectName("btn_pg")
        self.btn_gb = QtWidgets.QPushButton(self.frame_2)
        self.btn_gb.setGeometry(QtCore.QRect(10, 200, 120, 25))
        self.btn_gb.setMinimumSize(QtCore.QSize(120, 25))
        self.btn_gb.setObjectName("btn_gb")
        self.btn_call = QtWidgets.QPushButton(self.frame_2)
        self.btn_call.setGeometry(QtCore.QRect(10, 320, 120, 48))
        self.btn_call.setMinimumSize(QtCore.QSize(120, 48))
        self.btn_call.setObjectName("btn_call")
        self.btn_start_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_test.setGeometry(QtCore.QRect(110, 530, 140, 48))
        self.btn_start_test.setMinimumSize(QtCore.QSize(140, 48))
        self.btn_start_test.setObjectName("btn_start_test")
        self.gtu_static_2 = QtWidgets.QLabel(self.centralwidget)
        self.gtu_static_2.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gtu_static_2.sizePolicy().hasHeightForWidth())
        self.gtu_static_2.setSizePolicy(sizePolicy)
        self.gtu_static_2.setMinimumSize(QtCore.QSize(914, 594))
        self.gtu_static_2.setText("")
        self.gtu_static_2.setPixmap(QtGui.QPixmap("raw_img/гту_2.png"))
        self.gtu_static_2.setScaledContents(True)
        self.gtu_static_2.setObjectName("gtu_static_2")
        self.zuku = QtWidgets.QLabel(self.centralwidget)
        self.zuku.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zuku.sizePolicy().hasHeightForWidth())
        self.zuku.setSizePolicy(sizePolicy)
        self.zuku.setMinimumSize(QtCore.QSize(914, 594))
        self.zuku.setText("")
        self.zuku.setPixmap(QtGui.QPixmap("img/зуку.png"))
        self.zuku.setScaledContents(True)
        self.zuku.setObjectName("zuku")
        self.vtg_2 = QtWidgets.QLabel(self.centralwidget)
        self.vtg_2.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtg_2.sizePolicy().hasHeightForWidth())
        self.vtg_2.setSizePolicy(sizePolicy)
        self.vtg_2.setMinimumSize(QtCore.QSize(914, 594))
        self.vtg_2.setText("")
        self.vtg_2.setPixmap(QtGui.QPixmap("img/втг2.png"))
        self.vtg_2.setScaledContents(True)
        self.vtg_2.setObjectName("vtg_2")
        self.zuku_3 = QtWidgets.QLabel(self.centralwidget)
        self.zuku_3.setGeometry(QtCore.QRect(0, -70, 914, 594))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zuku_3.sizePolicy().hasHeightForWidth())
        self.zuku_3.setSizePolicy(sizePolicy)
        self.zuku_3.setMinimumSize(QtCore.QSize(914, 594))
        self.zuku_3.setText("")
        self.zuku_3.setPixmap(QtGui.QPixmap("img/зуку3.png"))
        self.zuku_3.setScaledContents(True)
        self.zuku_3.setObjectName("zuku_3")
        self.vtg_2.raise_()
        self.gtu_static_2.raise_()
        self.zuku.raise_()
        self.gtu_static.raise_()
        self.vtg.raise_()
        self.ctgt.raise_()
        self.label_8.raise_()
        self.zuku_3.raise_()
        self.btn_start_demo.raise_()
        self.btn_start_test.raise_()
        self.log.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тренажер оператора ГТУ"))
        self.btn_start_demo.setText(_translate("MainWindow", "Запустить\n"
"обучение"))
        self.label_8.setText(_translate("MainWindow", "T"))
        self.label_2.setText(_translate("MainWindow", "ЗУ КУ"))
        self.label.setText(_translate("MainWindow", "ЗУ ГТ"))
        self.label_3.setText(_translate("MainWindow", "ЗА ПГ"))
        self.label_4.setText(_translate("MainWindow", "ЗА ГБ"))
        self.label_5.setText(_translate("MainWindow", "СС"))
        self.btn_gt.setText(_translate("MainWindow", "Закрыть ЗУ ГТ"))
        self.btn_ku.setText(_translate("MainWindow", "Закрыть ЗУ КУ"))
        self.btn_vtg.setText(_translate("MainWindow", "Включить ВТГ"))
        self.btn_pg.setText(_translate("MainWindow", "Открыть ЗА ПГ"))
        self.btn_gb.setText(_translate("MainWindow", "Открыть ЗА ГБ"))
        self.btn_call.setText(_translate("MainWindow", "Звонок\n"
"диспетчеру"))
        self.btn_start_test.setText(_translate("MainWindow", "Запустить\n"
"тестирование"))

